[package]
name = "discord-stock-market-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
rand = "0.9.0"
tokio = {version = "1.32.0", features = ["full"]}
serenity = "0.12"
mongodb = {version = "3.2.1", features = ["sync"]}
serde_json = "*"
